[project]
name = "safe-task2-analysis"
version = "0.1.0"
description = "Task 2: Blockchain Event Analysis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
]